version: "3.7"
services: 
    app:
        build: 
            context: ./
            dockerfile: Dockerfile 
        ports: 
            - 3000:3000
        environment: 
            DATABASE: mongodb://mongo:27017/noteapp
            session_key: someRandomString    
    mongodb:
        image: mongo