# Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-noteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-noteapp
  template:
    metadata:
      labels:
        app: k8s-noteapp
    spec:
      containers:
        - name: app
          image: tolulopeayo/k8s-noteapp:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE
              value: mongodb://mongo:27017/noteapp
            - name: session_key
              value: someRandomString
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-noteapp
spec:
  selector:
    app: k8s-noteapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer 