# Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-noteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-noteapp
  template:
    metadata:
      labels:
        app: k8s-noteapp
    spec:
      containers:
        - name: app
          image: gcr.io/sca-tasks/noteapp@sha256:ffd6f8eff3e803a1ac68b1360caa842b4fdc8256b0effa65eb9f197f4b2ef5dc
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE
              value: mongodb://mongo:27017/noteapp
            - name: session_key
              value: someRandomString
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-noteapp
spec:
  selector:
    app: k8s-noteapp
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer 